### ISSUE TITLE
Can't compile HEAD

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/responsize#11]
When running closureCompiler task with Grunt, I get: 
```
rror: Command failed: src/rsz/wysiwyg/wyswyg.js:451: ERROR - actual parameter 2 of RszSelection.prototype.select does not match formal parameter
>> found   : (HTMLDocument|null)
>> required: (boolean|null|undefined)
>>     return this.rszSelection.select(node, this.document);
>>                                           ^
```
My HEAD is the last merge with @clemos ([commit](https://github.com/silexlabs/responsize/commit/bd7df1af9a56f2b05c4fefe5e88d1ab6ef96f77f))

**Comment by clemos** [comment]
it's fixed here : https://github.com/silexlabs/responsize/pull/10

**Comment by JbIPS** [comment]
Ok, so *someone* isn't doing his job (hum @lexoyo ) ^^.
Thx for the patch

**Comment by clemos** [comment]
well my patch was a bit random in the first place :p

**Comment by lexoyo** [comment]
hum, so sorry for the delay, i had not been notified :8ball: 
merged
